import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage
    const saved = localStorage.getItem('language') as Language;
    if (saved === 'en' || saved === 'es') {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key; // Return key if translation not found
      }
    }

    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// Translation data
const translations = {
  en: {
    common: {
      phone: '(604) 555-1234',
      email: 'maher@mbcrealtors.ca',
      location: 'Massachusetts & Connecticut',
      readMore: 'Read More',
      learnMore: 'Learn More',
      viewAll: 'View All',
      notFoundTitle: 'Page not found',
      notFoundDescription: "The page you're looking for doesn't exist or has been moved.",
      goHome: 'Go home',
      bed: 'Bed',
      bath: 'Bath',
      sqft: 'Sqft',
    },
    nav: {
      sellWithMaher: 'Sell With Maher',
      getYourOffer: 'Get Your Offer',
      investments: 'Investments',
      newBuilds: 'New Builds',
      listings: 'Listings',
      about: 'About',
      contact: 'Contact',
      call: 'Call',
      menu: 'Menu',
      close: 'Close',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
    },
    home: {
      heroEyebrow: 'Massachusetts & Connecticut',
      heroTitle: 'Broker and Real Estate Expert.',
      heroSubtitle: '20+ Years in Massachusetts and Connecticut.',
      heroDescription: 'Homes, multi-family, commercial, and land. Whether you are selling, buying, or building, you get one person who knows the market and handles it start to finish.',
      statSold: 'Sold',
      statAgents: 'Of all agents in MA',
      statClosed: 'Properties Closed',
      statReviews: '5-Star Reviews',
      statExperience: 'Years of Experience',
    },
    aboutMaher: {
      eyebrow: 'About Maher',
      title: 'Maher Khatib',
      subtitle: 'Broker and Real Estate Expert',
      para1: 'For more than 20 years, Maher has bought, sold, and built real estate across Massachusetts and Connecticut. Single-family homes. Multi-family buildings. Commercial property. Land.',
      para2: 'He has run projects from the first permit to the final walkthrough, so he knows what a property is really worth and what it will really take.',
      para3: 'That is why clients come back, and why they send their families.',
      meetMaher: 'Meet Maher',
      clientStories: 'Client Stories',
      imageAlt: 'Maher Khatib, Massachusetts and Connecticut real estate professional',
    },
    whatIDo: {
      eyebrow: 'Four Ways to Work Together',
      title: 'Four ways to work together',
      description: "Whether you're selling, buying or building — every engagement is treated as a private partnership, not a transaction.",
      sellTitle: 'Sell With Maher',
      sellDesc: 'List your home the right way. Smart pricing, real marketing, and a broker who works the offers until you get the best one.',
      offerTitle: 'Get Your Offer',
      offerDesc: 'A cash offer on your home in 48 hours. No repairs. No showings. No commission. You pick the closing date.',
      investmentsTitle: 'Investments',
      investmentsDesc: 'Multi-family, land, and development deals for buyers and partners who are building a portfolio.',
      newBuildsTitle: 'New Builds',
      newBuildsDesc: 'Ground-up construction across Metro Vancouver, BC, from land and permits through to the finished home.',
      explore: 'Explore',
    },
    findYourPlace: {
      eyebrow: 'Find Your Place',
      title: 'Where are you looking?',
      description: 'Our area guides offer deep insights into schools, amenities and market trends, so you can make confident decisions backed by local expertise.',
      browseAreas: 'Browse All Areas',
    },
    whyMaher: {
      eyebrow: 'Why Maher',
      title: 'He answers the phone.',
      description: 'A rare blend of deep local expertise, honest counsel and a marketing approach built for results, not for show.',
      meetMaher: 'Meet Maher',
      successStories: 'Success Stories',
      videoTitle1: 'Meet Maher',
      videoDesc1: 'Two minutes inside the philosophy, the process, and the results.',
      videoTitle2: 'Success Stories',
      videoDesc2: 'Hear directly from clients who closed with Maher.',
      watchFilm: 'Watch the film',
      filmDuration: '02:14',
    },
    serviceAreas: {
      eyebrow: 'Where I Work',
      title: 'Massachusetts and Connecticut.',
      massachusetts: 'Massachusetts',
      massachusettsCounties: 'Hampden County · Hampshire County · Berkshire County',
      massachusettsTowns: 'Featured towns: Springfield, MA · Westfield, MA · Chicopee, MA · Granby, MA',
      connecticut: 'Connecticut',
      connecticutCounties: 'Hartford County · Tolland County',
      connecticutTowns: 'Featured towns: Enfield, CT · Suffield, CT',
    },
    featuredListings: {
      eyebrow: 'Featured Listings',
      title: 'A private',
      titleItalic: 'portfolio',
      viewAll: 'View All',
      tagNewListing: 'New Listing',
      tagFeatured: 'Featured',
      tagCoastal: 'Coastal',
      tagDowntown: 'Downtown',
    },
    testimonials: {
      eyebrow: 'Testimonials',
      title: 'Real Results.',
      subtitle: 'Real Relationships.',
      description: 'Most of Maher\'s business comes from people he has already worked with. Some are on their tenth property with him. Some needed to sell fast and needed someone they could trust. Some just wanted the most money the market would give them.',
      circleText: 'Relationships · Community · Leadership ·',
      testimonial1Name: 'A. and J. T.',
      testimonial1Role: 'Home sale',
      testimonial1Location: 'Longmeadow, MA',
      testimonial1Quote: 'Two agents told me what my house was worth. Maher told me what it would actually sell for and why. It went under agreement in eleven days for more than either of the other numbers. He answered his phone every single time I called.',
      testimonial2Name: 'D. C.',
      testimonial2Role: 'Cash sale',
      testimonial2Location: 'Chicopee, MA',
      testimonial2Quote: 'I inherited my mother\'s house and I live three states away. I didn\'t have time to fix anything or sit through showings. Maher walked the property on a Tuesday and had an offer to me by Thursday. We closed on the date I picked. No repairs, no fees, nothing came out of the number he gave me.',
      testimonial3Name: 'R. M.',
      testimonial3Role: 'Multi-family investor',
      testimonial3Location: 'Springfield, MA',
      testimonial3Quote: 'I\'ve bought eight properties with Maher over the last six years. He calls me before a deal hits the market, and he tells me when a deal isn\'t worth it, which is the part most people won\'t do. He\'s made me money and he\'s saved me money.',
    },
    askMe: {
      eyebrow: 'Not sure which way to go?',
      title: 'Tell me about your property.',
      description: 'I will tell you what your options are, and there is no pressure either way.',
    },
    getYourOffer: {
      eyebrow: 'Get Your Offer',
      title: 'A cash offer in 48 hours.',
      description: 'No repairs, no showings, no waiting. Tell me about your home and get a direct offer.',
      requestOffer: 'Request My Offer',
      thankYou: 'Thank you — I\'ll be in touch',
    },
    footer: {
      description: 'A Massachusetts and Connecticut real estate practice led by broker Maher Khatib. Homes, multi-family, commercial, and land.',
      workWithMaher: 'Work With Maher',
      portfolio: 'Portfolio',
      about: 'About',
      reachOut: 'Reach Out',
      aboutMaher: 'About Maher',
      whereIWork: 'Where I Work',
      bookCall: 'Book a Call',
      license: '[Broker license number] · Equal Housing Opportunity',
      rights: 'All rights reserved.',
      privacy: 'Privacy',
      terms: 'Terms',
    },
    sell: {
      eyebrow: 'Sell With Maher',
      heroTitle: 'Sell your home with someone who has done this',
      heroTitleItalic: 'a thousand times.',
      heroSubtitle: 'Priced right, marketed properly, and negotiated hard. You get Maher, not a team member you have never met.',
      bookCall: 'Book a Call',
      resultsSold: 'Sold',
      resultsListToClose: 'List-to-close',
      resultsDOM: 'Median DOM',
      resultsAsking: 'Of asking',
      pillarsEyebrow: 'The Four Pillars',
      pillarsTitle: 'Fewer clients.',
      pillarsTitleItalic: 'Sharper outcomes.',
      pillarsDescription: 'A boutique listing practice. Homes sell better when someone cares.',
      pillarsQuote: 'The details are the strategy.',
      pillar1Title: 'Pricing Strategy',
      pillar1Desc: 'Priced on what is actually selling in your neighborhood right now, not on a guess.',
      pillar1Proof1: 'Comparative market analysis',
      pillar1Proof2: 'Buyer-pool modeling',
      pillar1Proof3: 'Weekly re-read',
      pillar2Title: 'Real Marketing',
      pillar2Desc: 'Professional photos, full listing exposure, and the property put in front of the buyers most likely to want it.',
      pillar2Proof1: 'Editorial photography',
      pillar2Proof2: 'Drone film',
      pillar2Proof3: 'Paid social + Google',
      pillar3Title: 'Firm Negotiation',
      pillar3Desc: 'Maher works the offers. Terms, timeline, and price, not just the top number on the page.',
      pillar3Proof1: 'Multi-offer strategy',
      pillar3Proof2: 'Contingency management',
      pillar3Proof3: 'Repair credit calibration',
      pillar4Title: 'Calm Closing',
      pillar4Desc: 'No drama. No surprises. Weekly check-ins, and Maher coordinates the inspectors, attorneys, and contractors himself.',
      pillar4Proof1: 'Weekly checkpoints',
      pillar4Proof2: 'Vendor coordination',
      pillar4Proof3: 'Post-close support',
      marketEyebrow: 'Live Market Pulse',
      marketTitle: 'What the market is',
      marketTitleItalic: 'actually doing.',
      marketUpdated: 'Updated weekly · Springfield · Granby · Longmeadow',
      marketMedianPrice: 'Median sale price',
      marketDaysOnMarket: 'Days on market',
      marketOverAsking: 'Over-asking rate',
      marketDemand: 'Buyer demand index',
      marketCTA: 'Curious what',
      marketCTAItalic: 'your home',
      marketCTAEnd: 'would land at today?',
      marketCTAButton: 'Get My Number',
      formEyebrow: 'Start the Conversation',
      formTitle: 'Tell me about your',
      formTitleItalic: 'home',
      formSubtitle: 'Private. Zero pressure.',
      formSubmit: 'Send Details',
    },
    offer: {
      eyebrow: 'Direct Buyer',
      heroTitle: 'Get a cash offer on your home',
      heroTitleItalic: 'in 48 hours.',
      heroSubtitle: 'No repairs. No showings. No commission. You pick the closing date.',
      requestOffer: 'Request Offer',
      bookCall: 'Book a Call',
      listingOnMarket: 'Listing on the market',
      howItWorksEyebrow: 'How It Works',
      howItWorksTitle: 'Four steps.',
      howItWorksTitleItalic: "That's it.",
      step1Title: 'Reach Out',
      step1Desc: 'Send your name, phone, and the property address. Takes a minute.',
      step2Title: 'Walk Through',
      step2Desc: 'Maher looks at the property. No cleaning up needed.',
      step3Title: 'Offer',
      step3Desc: 'You get a fair cash offer within 48 hours. No obligation.',
      step4Title: 'Close',
      step4Desc: 'You choose the closing date. Move when you are ready.',
      quote: 'A private offer,',
      quoteItalic: 'on your timeline',
      quoteEnd: '— with none of the drama.',
      compareEyebrow: 'Direct vs Traditional',
      compareTitle: 'One route is',
      compareTitleItalic: 'quieter',
      compareDirectPath: 'The Direct Path',
      compareSold: 'Sold.',
      compareSoldItalic: 'Quietly.',
      compareRowRepairs: 'Repairs',
      compareRowShowings: 'Showings',
      compareRowCommission: 'Commission',
      compareRowClosing: 'Closing date',
      compareRowTimeline: 'Timeline',
      compareDirectRepairs: 'No repairs',
      compareListingRepairs: 'Repairs usually required',
      compareDirectShowings: 'No showings',
      compareListingShowings: 'Public showings',
      compareDirectCommission: 'No commission',
      compareListingCommission: 'Commission comes out of your sale',
      compareDirectClosing: 'You pick the closing date',
      compareListingClosing: 'Closing date depends on the buyer',
      compareDirectTimeline: 'Offer in 48 hours',
      compareListingTimeline: 'Takes as long as it takes',
      compareDisclaimer: 'Neither one is wrong. If you have time and the house shows well, listing usually gets more. If you need speed and certainty, this is the faster road. Maher will tell you which one fits your situation, even if it is not the one that pays him.',
      estimatorEyebrow: 'Instant Estimate',
      estimatorTitle: 'A rough range,',
      estimatorTitleItalic: 'in seconds.',
      estimatorDesc: 'Slide to your rough home value. The exact number comes after a 20-minute walkthrough.',
      estimatorLabel: 'Estimated home value',
      estimatorLow: 'Direct offer — low',
      estimatorHigh: 'Direct offer — high',
      estimatorCTA: 'Lock in the Exact Number',
      whoForEyebrow: 'Who This Is For',
      whoForTitle: 'Owners who want',
      whoForTitleItalic: 'out cleanly',
      whoForInherited: 'Inherited',
      whoForNeedsRepairs: 'Needs repairs',
      whoForRelocation: 'Relocation',
      whoForTiredRental: 'Tired rental',
      whoForPrivate: 'Private sale',
      timelineEyebrow: '48-Hour Timeline',
      timelineTitle: 'From call',
      timelineTitleItalic: 'to closing table',
      timelineHour0: 'Hour 0',
      timelineHour0Label: 'First call',
      timelineHour24: 'Hour 24',
      timelineHour24Label: 'Walkthrough',
      timelineHour48: 'Hour 48',
      timelineHour48Label: 'Written offer',
      timelineDay14: 'Day 14',
      timelineDay14Label: 'Cash at close',
      formTitle: 'Request your',
      formTitleItalic: 'offer',
      formSubmit: 'Request My Offer',
      popupTitle: 'A direct offer on your home in 48 hours?',
      popupCTA: 'Request My Offer',
    },
    investments: {
      eyebrow: 'Investments',
      heroTitle: 'Investment and development opportunities in',
      heroTitleItalic: 'Metro Vancouver, BC.',
      heroSubtitle: 'Multi-family, land, and ground-up projects, sourced by a broker who has been buying in this market for 30 years.',
      open: 'Open',
      whatWeBringEyebrow: 'What We Bring',
      whatWeBring1: 'Multi-Family',
      whatWeBring1Desc: 'Two-family to small apartment buildings across the Springfield and Hartford corridor.',
      whatWeBring2: 'Land',
      whatWeBring2Desc: 'Buildable parcels with the permitting path already understood.',
      whatWeBring3: 'Development Projects',
      whatWeBring3Desc: 'Ground-up builds where partners can come in on the project rather than the finished house.',
      whatWeBring4: 'First Look',
      whatWeBring4Desc: 'Deals go to the list before they go anywhere else.',
      trackRecordEyebrow: 'Track Record',
      trackRecordTitle: 'Proven',
      trackRecordTitleItalic: 'performance',
      trackRecordDesc: 'Case studies and detailed track record coming soon. Contact for full investment history and references.',
      trackRecordCase1: 'Case Study #1',
      trackRecordCase1Title: '[Project Details Coming Soon]',
      trackRecordCase1Desc: 'Contact Maher Khatib Group for detailed investment case studies and historical performance data.',
      trackRecordCase2: 'Case Study #2',
      trackRecordCase2Title: '[Project Details Coming Soon]',
      trackRecordCase2Desc: 'Contact Maher Khatib Group for detailed investment case studies and historical performance data.',
      dealBookEyebrow: 'Active Deal Book',
      dealBookTitle: 'Current',
      dealBookTitleItalic: 'opportunities',
      dealBookUpdated: 'Redacted addresses · Full deck on request under NDA',
      dealBookRequestDeck: 'Request Full Deck',
      formEyebrow: 'Investor Inquiry',
      formTitle: 'Join the',
      formTitleItalic: 'investor list',
      formDesc: 'Get first look at multi-family, land, and development deals before they go anywhere else.',
      formOrBookCall: 'Or Book a Call',
      formSubmit: 'Join the List',
      formFocusLabel: 'What You Invest In',
      formFocusPlaceholder: 'Multi-family, land, development, all',
    },
    newBuilds: {
      eyebrow: 'New Builds',
      heroTitle: 'New construction across',
      heroTitleItalic: 'Metro Vancouver, BC.',
      heroSubtitle: 'Land, permits, and ground-up builds, managed start to finish.',
      heroCTA: 'See What Is In Progress',
      projectsEyebrow: 'Current Projects',
      projectsTitle: 'In',
      projectsTitleItalic: 'progress',
      projectStatus: 'In Progress',
      projectLotSize: 'Lot Size',
      projectHomesPlanned: 'Homes Planned',
      processEyebrow: 'The Process',
      processTitle: 'From land to',
      processTitleItalic: 'keys',
      processPhase1: 'Phase 01',
      processPhase1Title: 'Land',
      processPhase1Desc: 'Finding parcels that actually pencil out.',
      processPhase2: 'Phase 02',
      processPhase2Title: 'Permits and Plans',
      processPhase2Desc: 'Working the approvals so the project can move.',
      processPhase3: 'Phase 03',
      processPhase3Title: 'Build',
      processPhase3Desc: 'Ground-up construction, managed on site.',
      processPhase4: 'Phase 04',
      processPhase4Title: 'Sale',
      processPhase4Desc: 'The finished home, brought to market.',
      ctaEyebrow: 'Ready to Build',
      ctaTitle: 'Talk to Maher about',
      ctaTitleItalic: 'a build',
      ctaDesc: "Whether you're planning a custom home, spec build, or development project, reach out to discuss the next steps.",
      ctaCTA: 'Start a Conversation',
    },
    about: {
      eyebrow: 'Maher Khatib — Since 1995',
      heroTitle: 'Maher Khatib',
      heroSubtitle: 'Broker and Real Estate Expert. Metro Vancouver, BC.',
      statsSold: 'Sold',
      statsAgents: 'Of all agents in MA',
      statsClosed: 'Properties Closed',
      statsExperience: 'Years of Experience',
      bioEyebrow: 'Biography',
      bioPara1: 'Maher Khatib has spent more than 30 years in Metro Vancouver, BC real estate.',
      bioPara2: 'He works across homes, multi-family buildings, commercial property, and land. He has also run construction projects from the first permit through to the final walkthrough, which means he sees a property the way a builder does and prices it the way a broker does.',
      bioPara3: 'That combination is rare. It is also why his clients keep coming back, and why most of his business arrives by referral.',
      bioPara4: 'Whether the deal is a $400,000 home sale, a multi-family building, or a piece of land waiting to be developed, the process is the same: clear, calm, and handled personally.',
      chapter1Year: '1995',
      chapter1Title: 'Construction',
      chapter1Body: 'Framing walls before writing contracts.',
      chapter2Year: '2015',
      chapter2Title: 'Brokerage',
      chapter2Body: 'Same discipline. Different table.',
      chapter3Year: 'Today',
      chapter3Title: 'Broker & Real Estate Expert',
      chapter3Body: 'Brokerage, construction, and investment across Metro Vancouver, BC.',
      marqueeEyebrow: 'A Life in Homes',
      marqueeLocation: 'Springfield · Granby · Longmeadow',
      principlesEyebrow: 'Guiding Principles',
      principlesTitle: 'Four things',
      principlesTitleItalic: 'I refuse to bend on.',
      principlesDesc: 'The private rules that decide who I take on — and when I walk away.',
      principle1: 'Radical honesty on price.',
      principle2: 'Fewer clients, better work.',
      principle3: "The builder's eye stays on.",
      principle4: 'The phone gets answered.',
      ctaTitle: 'Ready to talk about',
      ctaTitleItalic: 'your next move',
      ctaCTA: 'Reach Out',
    },
    contact: {
      eyebrow: 'Contact',
      heroTitle: 'Tell me what you are',
      heroTitleItalic: 'working on.',
      heroSubtitle: 'Selling, buying, building, or just thinking about it. Reach out and we will figure out the right next step.',
      channelCall: 'Call',
      channelCallValue: '(604) 555-1234',
      channelCallDetail: 'Fastest reply. Mon–Sat, 8 to 8.',
      channelEmail: 'Email',
      channelEmailValue: 'maher@mbcrealtors.ca',
      channelEmailDetail: 'Reply within one business day.',
      channelBook: 'Book',
      channelBookValue: 'Private consultation',
      channelBookDetail: 'In person, phone, or video.',
      formEyebrow: 'Send a Message',
      formTitle: 'Send a',
      formTitleItalic: 'message',
      formSubmit: 'Send',
      mapEyebrow: 'Where I Work',
      mapTitle: 'Metro Vancouver,',
      mapTitleItalic: 'BC.',
    },
    form: {
      name: 'Name',
      phone: 'Phone',
      email: 'Email',
      message: 'Message',
      fullName: 'Full name',
      phonePlaceholder: '(604) 555-1234',
      emailPlaceholder: 'you@email.com',
      propertyAddress: 'Property Address',
      propertyAddressPlaceholder: 'Street, City',
      messagePlaceholder: 'Anything I should know?',
      whatCanIHelp: 'What Can I Help With',
      whatCanIHelpPlaceholder: 'Selling, buying, building, or just exploring options',
    },
  },
  es: {
    common: {
      phone: '(604) 555-1234',
      email: 'maher@mbcrealtors.ca',
      location: 'Massachusetts y Connecticut',
      readMore: 'Leer Más',
      learnMore: 'Aprender Más',
      viewAll: 'Ver Todo',
      notFoundTitle: 'Página no encontrada',
      notFoundDescription: 'La página que estás buscando no existe o ha sido movida.',
      goHome: 'Ir al inicio',
      bed: 'Habitación',
      bath: 'Baño',
      sqft: 'Pies²',
    },
    nav: {
      sellWithMaher: 'Vender con Maher',
      getYourOffer: 'Obtén tu Oferta',
      investments: 'Inversiones',
      newBuilds: 'Nuevas Construcciones',
      listings: 'Listados',
      about: 'Acerca de',
      contact: 'Contacto',
      call: 'Llamar',
      menu: 'Menú',
      close: 'Cerrar',
      openMenu: 'Abrir menú',
      closeMenu: 'Cerrar menú',
    },
    home: {
      heroEyebrow: 'Massachusetts y Connecticut',
      heroTitle: 'Corredor y Experto en Bienes Raíces.',
      heroSubtitle: 'Más de 20 años en Massachusetts y Connecticut.',
      heroDescription: 'Casas, multifamiliares, comerciales y terrenos. Ya sea que esté vendiendo, comprando o construyendo, obtiene una persona que conoce el mercado y lo maneja de principio a fin.',
      statSold: 'Vendido',
      statAgents: 'De todos los agentes en MA',
      statClosed: 'Propiedades Cerradas',
      statReviews: 'Reseñas de 5 Estrellas',
      statExperience: 'Años de Experiencia',
    },
    aboutMaher: {
      eyebrow: 'Acerca de Maher',
      title: 'Maher Khatib',
      subtitle: 'Corredor y Experto en Bienes Raíces',
      para1: 'Durante más de 20 años, Maher ha comprado, vendido y construido bienes raíces en Massachusetts y Connecticut. Casas unifamiliares. Edificios multifamiliares. Propiedad comercial. Terreno.',
      para2: 'Ha dirigido proyectos desde el primer permiso hasta la inspección final, por lo que sabe lo que realmente vale una propiedad y lo que realmente se necesita.',
      para3: 'Por eso los clientes regresan y por eso envían a sus familias.',
      meetMaher: 'Conocer a Maher',
      clientStories: 'Historias de Clientes',
      imageAlt: 'Maher Khatib, profesional de bienes raíces de Massachusetts y Connecticut',
    },
    whatIDo: {
      eyebrow: 'Cuatro Formas de Trabajar Juntos',
      title: 'Cuatro formas de trabajar juntos',
      description: 'Ya sea que esté vendiendo, comprando o construyendo, cada compromiso se trata como una asociación privada, no como una transacción.',
      sellTitle: 'Vender con Maher',
      sellDesc: 'Liste su casa de la manera correcta. Precios inteligentes, marketing real y un corredor que trabaja las ofertas hasta que obtenga la mejor.',
      offerTitle: 'Obtén tu Oferta',
      offerDesc: 'Una oferta en efectivo por su casa en 48 horas. Sin reparaciones. Sin visitas. Sin comisión. Usted elige la fecha de cierre.',
      investmentsTitle: 'Inversiones',
      investmentsDesc: 'Ofertas multifamiliares, de terrenos y de desarrollo para compradores y socios que están construyendo una cartera.',
      newBuildsTitle: 'Nuevas Construcciones',
      newBuildsDesc: 'Construcción desde cero en Metro Vancouver, BC, desde terrenos y permisos hasta la casa terminada.',
      explore: 'Explorar',
    },
    findYourPlace: {
      eyebrow: 'Encuentra tu Lugar',
      title: '¿Dónde estás buscando?',
      description: 'Nuestras guías de área ofrecen información detallada sobre escuelas, servicios y tendencias del mercado, para que pueda tomar decisiones con confianza respaldadas por experiencia local.',
      browseAreas: 'Ver Todas las Áreas',
    },
    whyMaher: {
      eyebrow: 'Por Qué Maher',
      title: 'Él contesta el teléfono.',
      description: 'Una combinación rara de experiencia local profunda, asesoramiento honesto y un enfoque de marketing diseñado para resultados, no para el espectáculo.',
      meetMaher: 'Conocer a Maher',
      successStories: 'Historias de Éxito',
      videoTitle1: 'Conocer a Maher',
      videoDesc1: 'Dos minutos dentro de la filosofía, el proceso y los resultados.',
      videoTitle2: 'Historias de Éxito',
      videoDesc2: 'Escuche directamente de los clientes que cerraron con Maher.',
      watchFilm: 'Ver la película',
      filmDuration: '02:14',
    },
    serviceAreas: {
      eyebrow: 'Dónde Trabajo',
      title: 'Massachusetts y Connecticut.',
      massachusetts: 'Massachusetts',
      massachusettsCounties: 'Condado de Hampden · Condado de Hampshire · Condado de Berkshire',
      massachusettsTowns: 'Ciudades destacadas: Springfield, MA · Westfield, MA · Chicopee, MA · Granby, MA',
      connecticut: 'Connecticut',
      connecticutCounties: 'Condado de Hartford · Condado de Tolland',
      connecticutTowns: 'Ciudades destacadas: Enfield, CT · Suffield, CT',
    },
    featuredListings: {
      eyebrow: 'Listados Destacados',
      title: 'Un portafolio',
      titleItalic: 'privado',
      viewAll: 'Ver Todos',
      tagNewListing: 'Nuevo Listado',
      tagFeatured: 'Destacado',
      tagCoastal: 'Costero',
      tagDowntown: 'Centro',
    },
    testimonials: {
      eyebrow: 'Testimonios',
      title: 'Resultados Reales.',
      subtitle: 'Relaciones Reales.',
      description: 'La mayoría de los negocios de Maher provienen de personas con las que ya ha trabajado. Algunos están en su décima propiedad con él. Algunos necesitaban vender rápido y necesitaban a alguien en quien pudieran confiar. Algunos solo querían el máximo dinero que el mercado les daría.',
      circleText: 'Relaciones · Comunidad · Liderazgo ·',
      testimonial1Name: 'A. y J. T.',
      testimonial1Role: 'Venta de casa',
      testimonial1Location: 'Longmeadow, MA',
      testimonial1Quote: 'Dos agentes me dijeron cuánto valía mi casa. Maher me dijo por cuánto se vendería realmente y por qué. Estuvo bajo acuerdo en once días por más que cualquiera de los otros números. Contestó su teléfono cada vez que llamé.',
      testimonial2Name: 'D. C.',
      testimonial2Role: 'Venta en efectivo',
      testimonial2Location: 'Chicopee, MA',
      testimonial2Quote: 'Heredé la casa de mi madre y vivo a tres estados de distancia. No tuve tiempo para arreglar nada ni sentarme a través de visitas. Maher recorrió la propiedad un martes y tuvo una oferta para mí el jueves. Cerramos en la fecha que elegí. Sin reparaciones, sin tarifas, nada salió del número que me dio.',
      testimonial3Name: 'R. M.',
      testimonial3Role: 'Inversor multifamiliar',
      testimonial3Location: 'Springfield, MA',
      testimonial3Quote: 'He comprado ocho propiedades con Maher en los últimos seis años. Me llama antes de que un trato llegue al mercado, y me dice cuándo un trato no vale la pena, que es la parte que la mayoría de la gente no hace. Me ha hecho ganar dinero y me ha ahorrado dinero.',
    },
    askMe: {
      eyebrow: '¿No estás seguro de qué camino tomar?',
      title: 'Háblame de tu propiedad.',
      description: 'Te diré cuáles son tus opciones, y no hay presión de ninguna manera.',
    },
    getYourOffer: {
      eyebrow: 'Obtén tu Oferta',
      title: 'Una oferta en efectivo en 48 horas.',
      description: 'Sin reparaciones, sin visitas, sin espera. Cuéntame sobre tu casa y obtén una oferta directa.',
      requestOffer: 'Solicitar Mi Oferta',
      thankYou: 'Gracias — Me pondré en contacto',
    },
    footer: {
      description: 'Una práctica de bienes raíces en Massachusetts y Connecticut dirigida por el corredor Maher Khatib. Casas, multifamiliares, comerciales y terrenos.',
      workWithMaher: 'Trabajar con Maher',
      portfolio: 'Portafolio',
      about: 'Acerca de',
      reachOut: 'Contactar',
      aboutMaher: 'Acerca de Maher',
      whereIWork: 'Dónde Trabajo',
      bookCall: 'Reservar una Llamada',
      license: '[Número de licencia de corredor] · Igualdad de Oportunidades de Vivienda',
      rights: 'Todos los derechos reservados.',
      privacy: 'Privacidad',
      terms: 'Términos',
    },
    sell: {
      eyebrow: 'Vender con Maher',
      heroTitle: 'Venda su casa con alguien que ha hecho esto',
      heroTitleItalic: 'mil veces.',
      heroSubtitle: 'Precio correcto, comercializado adecuadamente y negociado firmemente. Obtiene a Maher, no a un miembro del equipo que nunca ha conocido.',
      bookCall: 'Reservar una Llamada',
      resultsSold: 'Vendido',
      resultsListToClose: 'Lista a cierre',
      resultsDOM: 'Mediana DOM',
      resultsAsking: 'Del precio pedido',
      pillarsEyebrow: 'Los Cuatro Pilares',
      pillarsTitle: 'Menos clientes.',
      pillarsTitleItalic: 'Mejores resultados.',
      pillarsDescription: 'Una práctica de listado boutique. Las casas se venden mejor cuando a alguien le importa.',
      pillarsQuote: 'Los detalles son la estrategia.',
      pillar1Title: 'Estrategia de Precios',
      pillar1Desc: 'Con precio en lo que realmente se está vendiendo en su vecindario ahora mismo, no en una suposición.',
      pillar1Proof1: 'Análisis comparativo de mercado',
      pillar1Proof2: 'Modelado de grupo de compradores',
      pillar1Proof3: 'Revisión semanal',
      pillar2Title: 'Marketing Real',
      pillar2Desc: 'Fotos profesionales, exposición completa del listado y la propiedad puesta frente a los compradores más propensos a quererla.',
      pillar2Proof1: 'Fotografía editorial',
      pillar2Proof2: 'Película con dron',
      pillar2Proof3: 'Social pagado + Google',
      pillar3Title: 'Negociación Firme',
      pillar3Desc: 'Maher trabaja las ofertas. Términos, cronograma y precio, no solo el número superior en la página.',
      pillar3Proof1: 'Estrategia de múltiples ofertas',
      pillar3Proof2: 'Gestión de contingencias',
      pillar3Proof3: 'Calibración de crédito de reparación',
      pillar4Title: 'Cierre Tranquilo',
      pillar4Desc: 'Sin drama. Sin sorpresas. Controles semanales, y Maher coordina a los inspectores, abogados y contratistas él mismo.',
      pillar4Proof1: 'Puntos de control semanales',
      pillar4Proof2: 'Coordinación de proveedores',
      pillar4Proof3: 'Soporte posterior al cierre',
      marketEyebrow: 'Pulso del Mercado en Vivo',
      marketTitle: 'Lo que el mercado está',
      marketTitleItalic: 'realmente haciendo.',
      marketUpdated: 'Actualizado semanalmente · Springfield · Granby · Longmeadow',
      marketMedianPrice: 'Precio de venta medio',
      marketDaysOnMarket: 'Días en el mercado',
      marketOverAsking: 'Tasa sobre el precio pedido',
      marketDemand: 'Índice de demanda del comprador',
      marketCTA: 'Curioso qué',
      marketCTAItalic: 'tu casa',
      marketCTAEnd: '¿valdría hoy?',
      marketCTAButton: 'Obtener Mi Número',
      formEyebrow: 'Iniciar la Conversación',
      formTitle: 'Cuéntame sobre tu',
      formTitleItalic: 'casa',
      formSubtitle: 'Privado. Cero presión.',
      formSubmit: 'Enviar Detalles',
    },
    offer: {
      eyebrow: 'Comprador Directo',
      heroTitle: 'Obtenga una oferta en efectivo por su casa',
      heroTitleItalic: 'en 48 horas.',
      heroSubtitle: 'Sin reparaciones. Sin visitas. Sin comisión. Usted elige la fecha de cierre.',
      requestOffer: 'Solicitar Oferta',
      bookCall: 'Reservar una Llamada',
      listingOnMarket: 'Listar en el mercado',
      howItWorksEyebrow: 'Cómo Funciona',
      howItWorksTitle: 'Cuatro pasos.',
      howItWorksTitleItalic: 'Eso es todo.',
      step1Title: 'Comunícate',
      step1Desc: 'Envía tu nombre, teléfono y la dirección de la propiedad. Toma un minuto.',
      step2Title: 'Recorrido',
      step2Desc: 'Maher mira la propiedad. No necesita limpieza.',
      step3Title: 'Oferta',
      step3Desc: 'Recibes una oferta justa en efectivo en 48 horas. Sin obligación.',
      step4Title: 'Cerrar',
      step4Desc: 'Eliges la fecha de cierre. Múdate cuando estés listo.',
      quote: 'Una oferta privada,',
      quoteItalic: 'en tu cronograma',
      quoteEnd: '— sin ningún drama.',
      compareEyebrow: 'Directo vs Tradicional',
      compareTitle: 'Una ruta es',
      compareTitleItalic: 'más tranquila',
      compareDirectPath: 'El Camino Directo',
      compareSold: 'Vendido.',
      compareSoldItalic: 'Tranquilamente.',
      compareRowRepairs: 'Reparaciones',
      compareRowShowings: 'Visitas',
      compareRowCommission: 'Comisión',
      compareRowClosing: 'Fecha de cierre',
      compareRowTimeline: 'Cronograma',
      compareDirectRepairs: 'Sin reparaciones',
      compareListingRepairs: 'Reparaciones generalmente requeridas',
      compareDirectShowings: 'Sin visitas',
      compareListingShowings: 'Visitas públicas',
      compareDirectCommission: 'Sin comisión',
      compareListingCommission: 'La comisión sale de tu venta',
      compareDirectClosing: 'Tú eliges la fecha de cierre',
      compareListingClosing: 'La fecha de cierre depende del comprador',
      compareDirectTimeline: 'Oferta en 48 horas',
      compareListingTimeline: 'Toma el tiempo que sea necesario',
      compareDisclaimer: 'Ninguno está mal. Si tienes tiempo y la casa se ve bien, listar generalmente obtiene más. Si necesitas velocidad y certeza, este es el camino más rápido. Maher te dirá cuál se adapta a tu situación, incluso si no es el que le paga.',
      estimatorEyebrow: 'Estimación Instantánea',
      estimatorTitle: 'Un rango aproximado,',
      estimatorTitleItalic: 'en segundos.',
      estimatorDesc: 'Desliza para tu valor aproximado de casa. El número exacto viene después de un recorrido de 20 minutos.',
      estimatorLabel: 'Valor estimado de la casa',
      estimatorLow: 'Oferta directa — baja',
      estimatorHigh: 'Oferta directa — alta',
      estimatorCTA: 'Obtener el Número Exacto',
      whoForEyebrow: 'Para Quién Es Esto',
      whoForTitle: 'Propietarios que quieren',
      whoForTitleItalic: 'salir limpiamente',
      whoForInherited: 'Heredado',
      whoForNeedsRepairs: 'Necesita reparaciones',
      whoForRelocation: 'Reubicación',
      whoForTiredRental: 'Alquiler cansado',
      whoForPrivate: 'Venta privada',
      timelineEyebrow: 'Cronograma de 48 Horas',
      timelineTitle: 'Desde la llamada',
      timelineTitleItalic: 'hasta la mesa de cierre',
      timelineHour0: 'Hora 0',
      timelineHour0Label: 'Primera llamada',
      timelineHour24: 'Hora 24',
      timelineHour24Label: 'Recorrido',
      timelineHour48: 'Hora 48',
      timelineHour48Label: 'Oferta escrita',
      timelineDay14: 'Día 14',
      timelineDay14Label: 'Efectivo al cierre',
      formTitle: 'Solicita tu',
      formTitleItalic: 'oferta',
      formSubmit: 'Solicitar Mi Oferta',
      popupTitle: '¿Una oferta directa en tu casa en 48 horas?',
      popupCTA: 'Solicitar Mi Oferta',
    },
    investments: {
      eyebrow: 'Inversiones',
      heroTitle: 'Oportunidades de inversión y desarrollo en',
      heroTitleItalic: 'Metro Vancouver, BC.',
      heroSubtitle: 'Proyectos multifamiliares, de terrenos y desde cero, obtenidos por un corredor que ha estado comprando en este mercado durante 30 años.',
      open: 'Abierto',
      whatWeBringEyebrow: 'Lo Que Aportamos',
      whatWeBring1: 'Multifamiliar',
      whatWeBring1Desc: 'De dos familias a pequeños edificios de apartamentos en el corredor de Springfield y Hartford.',
      whatWeBring2: 'Terreno',
      whatWeBring2Desc: 'Parcelas edificables con el camino de permisos ya entendido.',
      whatWeBring3: 'Proyectos de Desarrollo',
      whatWeBring3Desc: 'Construcciones desde cero donde los socios pueden entrar en el proyecto en lugar de la casa terminada.',
      whatWeBring4: 'Primera Vista',
      whatWeBring4Desc: 'Las ofertas van a la lista antes que a cualquier otro lugar.',
      trackRecordEyebrow: 'Historial',
      trackRecordTitle: 'Rendimiento',
      trackRecordTitleItalic: 'comprobado',
      trackRecordDesc: 'Estudios de caso e historial detallado próximamente. Contacta para el historial de inversión completo y referencias.',
      trackRecordCase1: 'Estudio de Caso #1',
      trackRecordCase1Title: '[Detalles del Proyecto Próximamente]',
      trackRecordCase1Desc: 'Contacta a Maher Khatib Group para estudios de caso de inversión detallados y datos de rendimiento histórico.',
      trackRecordCase2: 'Estudio de Caso #2',
      trackRecordCase2Title: '[Detalles del Proyecto Próximamente]',
      trackRecordCase2Desc: 'Contacta a Maher Khatib Group para estudios de caso de inversión detallados y datos de rendimiento histórico.',
      dealBookEyebrow: 'Libro de Ofertas Activas',
      dealBookTitle: 'Oportunidades',
      dealBookTitleItalic: 'actuales',
      dealBookUpdated: 'Direcciones censuradas · Paquete completo bajo solicitud con NDA',
      dealBookRequestDeck: 'Solicitar Paquete Completo',
      formEyebrow: 'Consulta de Inversores',
      formTitle: 'Únete a la',
      formTitleItalic: 'lista de inversores',
      formDesc: 'Obtén la primera vista de ofertas multifamiliares, de terrenos y de desarrollo antes que nadie más.',
      formOrBookCall: 'O Reservar una Llamada',
      formSubmit: 'Unirse a la Lista',
      formFocusLabel: 'En Qué Inviertes',
      formFocusPlaceholder: 'Multifamiliar, terreno, desarrollo, todo',
    },
    newBuilds: {
      eyebrow: 'Nuevas Construcciones',
      heroTitle: 'Nueva construcción en',
      heroTitleItalic: 'Metro Vancouver, BC.',
      heroSubtitle: 'Terreno, permisos y construcciones desde cero, gestionadas de principio a fin.',
      heroCTA: 'Ver Lo Que Está En Progreso',
      projectsEyebrow: 'Proyectos Actuales',
      projectsTitle: 'En',
      projectsTitleItalic: 'progreso',
      projectStatus: 'En Progreso',
      projectLotSize: 'Tamaño del Lote',
      projectHomesPlanned: 'Casas Planificadas',
      processEyebrow: 'El Proceso',
      processTitle: 'Del terreno a las',
      processTitleItalic: 'llaves',
      processPhase1: 'Fase 01',
      processPhase1Title: 'Terreno',
      processPhase1Desc: 'Encontrar parcelas que realmente funcionen.',
      processPhase2: 'Fase 02',
      processPhase2Title: 'Permisos y Planos',
      processPhase2Desc: 'Trabajar las aprobaciones para que el proyecto pueda avanzar.',
      processPhase3: 'Fase 03',
      processPhase3Title: 'Construcción',
      processPhase3Desc: 'Construcción desde cero, gestionada en el sitio.',
      processPhase4: 'Fase 04',
      processPhase4Title: 'Venta',
      processPhase4Desc: 'La casa terminada, llevada al mercado.',
      ctaEyebrow: 'Listo para Construir',
      ctaTitle: 'Habla con Maher sobre',
      ctaTitleItalic: 'una construcción',
      ctaDesc: 'Ya sea que estés planeando una casa personalizada, una construcción especulativa o un proyecto de desarrollo, comunícate para discutir los próximos pasos.',
      ctaCTA: 'Iniciar una Conversación',
    },
    about: {
      eyebrow: 'Maher Khatib — Desde 1995',
      heroTitle: 'Maher Khatib',
      heroSubtitle: 'Corredor y Experto en Bienes Raíces. Metro Vancouver, BC.',
      statsSold: 'Vendido',
      statsAgents: 'De todos los agentes en MA',
      statsClosed: 'Propiedades Cerradas',
      statsExperience: 'Años de Experiencia',
      bioEyebrow: 'Biografía',
      bioPara1: 'Maher Khatib ha pasado más de 30 años en bienes raíces de Metro Vancouver, BC.',
      bioPara2: 'Trabaja en casas, edificios multifamiliares, propiedad comercial y terrenos. También ha dirigido proyectos de construcción desde el primer permiso hasta la inspección final, lo que significa que ve una propiedad como lo hace un constructor y la cotiza como lo hace un corredor.',
      bioPara3: 'Esa combinación es rara. También es por eso que sus clientes siguen regresando y por qué la mayoría de sus negocios llegan por referencia.',
      bioPara4: 'Ya sea que el trato sea una venta de casa de $400,000, un edificio multifamiliar o un terreno esperando ser desarrollado, el proceso es el mismo: claro, tranquilo y manejado personalmente.',
      chapter1Year: '1995',
      chapter1Title: 'Construcción',
      chapter1Body: 'Enmarcando paredes antes de escribir contratos.',
      chapter2Year: '2015',
      chapter2Title: 'Corretaje',
      chapter2Body: 'Misma disciplina. Mesa diferente.',
      chapter3Year: 'Hoy',
      chapter3Title: 'Corredor y Experto en Bienes Raíces',
      chapter3Body: 'Corretaje, construcción e inversión en Metro Vancouver, BC.',
      marqueeEyebrow: 'Una Vida en Casas',
      marqueeLocation: 'Springfield · Granby · Longmeadow',
      principlesEyebrow: 'Principios Rectores',
      principlesTitle: 'Cuatro cosas',
      principlesTitleItalic: 'en las que me niego a ceder.',
      principlesDesc: 'Las reglas privadas que deciden a quién acepto y cuándo me alejo.',
      principle1: 'Honestidad radical en el precio.',
      principle2: 'Menos clientes, mejor trabajo.',
      principle3: 'El ojo del constructor permanece activo.',
      principle4: 'El teléfono se contesta.',
      ctaTitle: 'Listo para hablar sobre',
      ctaTitleItalic: 'tu próximo movimiento',
      ctaCTA: 'Contactar',
    },
    contact: {
      eyebrow: 'Contacto',
      heroTitle: 'Cuéntame en qué estás',
      heroTitleItalic: 'trabajando.',
      heroSubtitle: 'Vendiendo, comprando, construyendo o simplemente pensando en ello. Comunícate y descubriremos el siguiente paso correcto.',
      channelCall: 'Llamar',
      channelCallValue: '(604) 555-1234',
      channelCallDetail: 'Respuesta más rápida. Lun–Sáb, 8 a 8.',
      channelEmail: 'Email',
      channelEmailValue: 'maher@mbcrealtors.ca',
      channelEmailDetail: 'Respuesta en un día hábil.',
      channelBook: 'Reservar',
      channelBookValue: 'Consulta privada',
      channelBookDetail: 'En persona, por teléfono o video.',
      formEyebrow: 'Enviar un Mensaje',
      formTitle: 'Enviar un',
      formTitleItalic: 'mensaje',
      formSubmit: 'Enviar',
      mapEyebrow: 'Dónde Trabajo',
      mapTitle: 'Metro Vancouver,',
      mapTitleItalic: 'BC.',
    },
    form: {
      name: 'Nombre',
      phone: 'Teléfono',
      email: 'Correo Electrónico',
      message: 'Mensaje',
      fullName: 'Nombre completo',
      phonePlaceholder: '(604) 555-1234',
      emailPlaceholder: 'tu@email.com',
      propertyAddress: 'Dirección de la Propiedad',
      propertyAddressPlaceholder: 'Calle, Ciudad',
      messagePlaceholder: '¿Algo que deba saber?',
      whatCanIHelp: 'En Qué Puedo Ayudar',
      whatCanIHelpPlaceholder: 'Vender, comprar, construir o solo explorar opciones',
    },
  },
};
