/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SellRouteImport } from './routes/sell'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as NewBuildsRouteImport } from './routes/new-builds'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminListingsIndexRouteImport } from './routes/admin.listings.index'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminListingsNewRouteImport } from './routes/admin.listings.new'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin.posts.$id.edit'
import { Route as AdminListingsIdEditRouteImport } from './routes/admin.listings.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const NewBuildsRoute = NewBuildsRouteImport.update({
  id: '/new-builds',
  path: '/new-builds',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsIndexRoute = AdminListingsIndexRouteImport.update({
  id: '/admin/listings/',
  path: '/admin/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/admin/posts/new',
  path: '/admin/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsNewRoute = AdminListingsNewRouteImport.update({
  id: '/admin/listings/new',
  path: '/admin/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/admin/posts/$id/edit',
  path: '/admin/posts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsIdEditRoute = AdminListingsIdEditRouteImport.update({
  id: '/admin/listings/$id/edit',
  path: '/admin/listings/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/investments': typeof InvestmentsRoute
  '/listings': typeof ListingsRoute
  '/new-builds': typeof NewBuildsRoute
  '/offer': typeof OfferRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/investments': typeof InvestmentsRoute
  '/listings': typeof ListingsRoute
  '/new-builds': typeof NewBuildsRoute
  '/offer': typeof OfferRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/listings': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/investments': typeof InvestmentsRoute
  '/listings': typeof ListingsRoute
  '/new-builds': typeof NewBuildsRoute
  '/offer': typeof OfferRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/investments'
    | '/listings'
    | '/new-builds'
    | '/offer'
    | '/sell'
    | '/sitemap.xml'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/listings/new'
    | '/admin/posts/new'
    | '/admin/listings/'
    | '/admin/listings/$id/edit'
    | '/admin/posts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/investments'
    | '/listings'
    | '/new-builds'
    | '/offer'
    | '/sell'
    | '/sitemap.xml'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/admin/listings/new'
    | '/admin/posts/new'
    | '/admin/listings'
    | '/admin/listings/$id/edit'
    | '/admin/posts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/investments'
    | '/listings'
    | '/new-builds'
    | '/offer'
    | '/sell'
    | '/sitemap.xml'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/listings/new'
    | '/admin/posts/new'
    | '/admin/listings/'
    | '/admin/listings/$id/edit'
    | '/admin/posts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  InvestmentsRoute: typeof InvestmentsRoute
  ListingsRoute: typeof ListingsRoute
  NewBuildsRoute: typeof NewBuildsRoute
  OfferRoute: typeof OfferRoute
  SellRoute: typeof SellRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  AdminListingsNewRoute: typeof AdminListingsNewRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminListingsIndexRoute: typeof AdminListingsIndexRoute
  AdminListingsIdEditRoute: typeof AdminListingsIdEditRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-builds': {
      id: '/new-builds'
      path: '/new-builds'
      fullPath: '/new-builds'
      preLoaderRoute: typeof NewBuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/': {
      id: '/admin/listings/'
      path: '/admin/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/admin/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/new': {
      id: '/admin/listings/new'
      path: '/admin/listings/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/admin/posts/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/$id/edit': {
      id: '/admin/listings/$id/edit'
      path: '/admin/listings/$id/edit'
      fullPath: '/admin/listings/$id/edit'
      preLoaderRoute: typeof AdminListingsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  InvestmentsRoute: InvestmentsRoute,
  ListingsRoute: ListingsRoute,
  NewBuildsRoute: NewBuildsRoute,
  OfferRoute: OfferRoute,
  SellRoute: SellRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  AdminListingsNewRoute: AdminListingsNewRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminListingsIndexRoute: AdminListingsIndexRoute,
  AdminListingsIdEditRoute: AdminListingsIdEditRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
